apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-python.fullname" . }}
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: pod-port1
      protocol: TCP
      name: srv1
    - port: {{ .Values.service.port2 }}
      targetPort: pod-port2
      protocol: TCP
      name: srv2
  selector:
    {{- include "app-python.selectorLabels" . | nindent 4 }}
